version: '2'

services:
    portainer:
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock #--ssl
    #environment:
      #- sslcert=/certs/portainer.crt
      #- sslkey=/certs/portainer.key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
      #- ./portainer_certs:/certs
    ports:
      - "8080:9000"
      #- "443:9000"
